# Generated by Django 5.0.4 on 2024-11-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('goals_scored', models.IntegerField()),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
